version: "3.1"

services:
  db:
    image: postgres:16
    # restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: root
    ports:
      - "5433:5432"
    # volumes:
    #   - ../data:/var/lib/postgresql/data
  redis:
    # restart: always
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ../redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_DEFAULT_BUCKETS=mybucket

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local