# Generated by Django 5.1 on 2024-08-28 08:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(default='', help_text='App key lấy từ tiktok app for developer', max_length=500)),
                ('secret', models.CharField(default='', help_text='App secret lấy từ tiktok app for developer', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='BuyedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(help_text='Package_id da duoc buy label', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ErrorCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FlashShipPODVariantList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.IntegerField()),
                ('color', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('SHIRT', 'Shirt'), ('HOODIE', 'Hoodie'), ('SWEATSHIRT', 'Sweatshirt')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GroupCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='chua co ten', help_text='ten cua phong ban', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NotiMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500, verbose_name='type of notification')),
                ('message', models.TextField(verbose_name='message for notification')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=500)),
                ('buyer_first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('buyer_last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('buyer_email', models.CharField(max_length=500, null=True)),
                ('buyer_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer_address1', models.CharField(blank=True, max_length=1000, null=True)),
                ('buyer_address2', models.CharField(blank=True, max_length=1000)),
                ('buyer_city', models.CharField(blank=True, max_length=500, null=True)),
                ('buyer_province_code', models.CharField(blank=True, max_length=20, null=True)),
                ('buyer_zip', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_country_code', models.CharField(max_length=2, null=True)),
                ('shipment', models.IntegerField(null=True)),
                ('linkLabel', models.CharField(blank=True, max_length=1000, null=True)),
                ('fulfillment_name', models.CharField(max_length=500, null=True)),
                ('order_code', models.CharField(blank=True, max_length=500, null=True)),
                ('pack_id', models.CharField(blank=True, max_length=500, null=True)),
                ('package_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_token', models.CharField(max_length=255, null=True, verbose_name='Verify token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserSendPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesignSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(help_text='SKU ID', max_length=500)),
                ('product_name', models.CharField(help_text='product_name', max_length=500)),
                ('variation', models.CharField(help_text='variation', max_length=500)),
                ('image_front', models.CharField(blank=True, help_text='image_front', max_length=500, null=True)),
                ('image_back', models.CharField(blank=True, help_text='image_back', max_length=500, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.groupcustom')),
            ],
        ),
        migrations.CreateModel(
            name='DesignSkuChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_data', models.TextField(null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('design_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.designsku')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlashShipAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('pass_word', models.CharField(blank=True, max_length=1000, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='api.groupcustom')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.imagefolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_image')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(default='', max_length=255, null=True)),
                ('image_name', models.CharField(default='no name', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.imagefolder')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.CharField(blank=True, max_length=500, null=True)),
                ('printer_design_front_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('printer_design_back_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.package')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_code', models.CharField(default='', help_text='Shop id lấy từ shop code', max_length=500)),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500, null=True)),
                ('auth_code', models.CharField(max_length=500)),
                ('grant_type', models.CharField(default='authorized_code', max_length=500)),
                ('shop_name', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('shop_id_author', models.CharField(max_length=500, null=True)),
                ('shop_cipher', models.CharField(max_length=500, null=True)),
                ('group_custom_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.groupcustom')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shop')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shop'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='mark as read')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_noti', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='api.notimessage')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_noti', to='api.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_template', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('category_id', models.JSONField()),
                ('description', models.TextField(default='', max_length=50000)),
                ('is_cod_open', models.BooleanField(default=False)),
                ('package_height', models.FloatField(default=1)),
                ('package_length', models.FloatField(default=1)),
                ('package_weight', models.FloatField(default=1)),
                ('package_width', models.FloatField(default=1)),
                ('sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('types', models.JSONField()),
                ('badWords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, null=True, size=None)),
                ('suffixTitle', models.CharField(default='', max_length=500, null=True)),
                ('size_chart', models.TextField(null=True)),
                ('fixed_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20000), default=list, null=True, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Admin'), (1, 'Manager'), (2, 'Seller')], default=2, verbose_name='Role')),
                ('group_custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groupcustom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group_custom')},
            },
        ),
    ]
