# Generated by Django 5.1 on 2024-09-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_templates_fixed_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsku',
            name='image_back',
            field=models.CharField(blank=True, help_text='mockup_back', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='designsku',
            name='image_front',
            field=models.CharField(blank=True, help_text='mockup_front', max_length=500, null=True),
        ),
    ]
