# Generated by Django 5.1 on 2024-09-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_designsku_image_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsku',
            name='mockup_back',
            field=models.CharField(blank=True, help_text='mockup_back', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='designsku',
            name='mockup_front',
            field=models.CharField(blank=True, help_text='mockup_front', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='designsku',
            name='image_back',
            field=models.CharField(blank=True, help_text='image_back', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='designsku',
            name='image_front',
            field=models.CharField(blank=True, help_text='image_front', max_length=500, null=True),
        ),
    ]
