# Generated by Django 5.1 on 2024-09-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_templates_colors_alter_templates_sizes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CkfVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=500)),
                ('product_type', models.CharField(choices=[('SHIRT', 'Shirt'), ('HOODIE', 'Hoodie'), ('SWEATSHIRT', 'Sweatshirt')], max_length=20)),
            ],
        ),
    ]
