# Generated by Django 5.1 on 2024-10-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ckfvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='option1',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='templates',
            name='option2',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='templates',
            name='option3',
            field=models.JSONField(null=True),
        ),
    ]
