# Generated by Django 5.1 on 2024-10-13 18:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_templates_option1_templates_option2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='templates',
            name='sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='templates',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, null=True, size=None),
        ),
    ]
