# Generated by Django 5.1 on 2024-10-18 04:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_templates_colors_alter_templates_sizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='images_link_variant',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500, null=True), null=True, size=None),
        ),
    ]
