# Generated by Django 5.1 on 2024-10-18 04:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_templates_images_link_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='images_link_variant',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500, null=True), default=list, null=True, size=None),
        ),
    ]
