# Generated by Django 5.1 on 2024-10-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_templates_images_link_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
