# Generated by Django 5.1 on 2024-11-13 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_shop_shop_description'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='productpackage',
            name='mock_up_back',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='mock_up_front',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
