# Generated by Django 5.1 on 2024-11-13 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_package_created_at_package_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpackage',
            old_name='mock_up_back',
            new_name='mock_up_back_url',
        ),
        migrations.RenameField(
            model_name='productpackage',
            old_name='mock_up_front',
            new_name='mock_up_front_url',
        ),
      
    ]
