# Generated by Django 5.1 on 2024-11-14 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_mock_up_back_productpackage_mock_up_back_url_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='productpackage',
            name='color',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='size',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='style',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
