# Generated by Django 5.1 on 2024-11-14 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_package_created_at_package_seller_and_more'),
    ]

    operations = [
      
        migrations.AddField(
            model_name='package',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
