# Generated by Django 5.1 on 2024-11-15 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_package_created_at_package_seller_and_more'),
    ]

    operations = [
     
        migrations.AddField(
            model_name='productpackage',
            name='product_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
