# Generated by Django 5.1 on 2024-11-21 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_package_created_at_package_seller_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('no_design', 'Chưa có design'), ('has_design', 'Đã tồn tại design'), ('print_pending', 'Đang inpet'), ('printed', 'Đã inpet'), ('in_production', 'Đang sản xuất'), ('production_done', 'Đã sản xuất xong'), ('shipping_to_us', 'Đang ship đến Mỹ'), ('shipped_to_us', 'Đã ship đến Mỹ'), ('shipping_within_us', 'Đang ship trong Mỹ'), ('delivered_to_customer', 'Đã giao tới khách hàng'), ('cancelled', 'Cancel')], default='no_design', max_length=50),
        ),
    ]
