# Generated by Django 5.1 on 2024-11-23 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_package_created_at_package_seller_package_status'),
    ]

    operations = [
     
        migrations.AddField(
            model_name='productpackage',
            name='sku_custom',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
