# Generated by Django 5.1 on 2024-12-02 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_package_created_at_package_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkey',
            name='link_service',
            field=models.CharField(default='', help_text='Link service lấy từ tiktok app for developer', max_length=500),
        ),
       
        migrations.AddField(
            model_name='shop',
            name='app_key',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='app_secret',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='service_link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
