# Generated by Django 5.1 on 2024-12-20 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_appkey_link_service_package_created_at_and_more'),
    ]

    operations = [


        migrations.AddField(
            model_name='package',
            name='supify_create_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_packages', to='api.customuser'),
        ),
        migrations.AddField(
            model_name='package',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
      
    ]
