# Generated by Django 5.1 on 2024-12-20 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_package_created_at_package_seller_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('init', 'khởi tạo'), ('no_design', 'Chưa có design'), ('has_design', 'Đã tồn tại design'), ('print_pending', 'Đang inpet'), ('printed', 'Đã inpet'), ('in_production', 'Đang sản xuất'), ('production_done', 'Đã sản xuất xong'), ('shipping_to_us', 'Đang ship đến Mỹ'), ('shipped_to_us', 'Đã ship đến Mỹ'), ('shipping_within_us', 'Đang ship trong Mỹ'), ('delivered_to_customer', 'Đã giao tới khách hàng'), ('cancelled', 'Cancel'), ('can_not_produce', 'Không thể sản xuất'), ('lack_of_pet', 'chưa có pet'), ('wrong_design', 'sai design'), ('wrong_mockkup', 'sai mockup'), ('forwarded_to_supify', 'Đã chuyển tiếp đến xưởng supify'), ('sent_to_onos', 'Đã chuyển cho onos'), ('fullfilled', 'Đã fullfill'), ('reforwarded_to_hall', 'Đã chuyển lại cho sảnh')], default='init', max_length=50),
        ),
    ]
