# Generated by Django 5.1 on 2024-12-24 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_package_created_at_package_seller_and_more'),
    ]

    operations = [
     
        migrations.AddField(
            model_name='package',
            name='seller_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
