# Generated by Django 5.1 on 2025-01-07 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_package_created_at_package_seller_and_more'),
    ]

    operations = [
     
        migrations.AddField(
            model_name='package',
            name='number_sort',
            field=models.IntegerField(null=True),
        )
      
    ]
