# Generated by Django 5.1 on 2025-03-02 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_package_created_at_package_number_sort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_packages', to='api.customuser'),
        ),
        migrations.AddField(
            model_name='templates',
            name='customTemplateData',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='templates',
            name='templateType',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
