# Generated by Django 5.1 on 2025-03-09 14:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_package_created_at_package_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='attributes',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='templates',
            name='fixed_image_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500, null=True), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='templates',
            name='size_chart_url',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
