# Generated by Django 5.1 on 2025-06-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_templates_attributes_templates_fixed_image_urls_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="seller",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
