# Generated by Django 5.1 on 2025-07-29 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_alter_package_seller"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="designsku",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="designsku",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_designs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="designsku",
            name="type_print",
            field=models.CharField(
                blank=True, help_text="type_print", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="designsku",
            name="type_shirt",
            field=models.CharField(
                blank=True, help_text="type_shirt", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="designsku",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
