# Generated by Django 5.1 on 2025-08-05 04:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_designsku_created_at_designsku_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergroup",
            name="role",
            field=models.IntegerField(
                choices=[
                    (0, "Admin"),
                    (1, "Manager"),
                    (2, "Seller"),
                    (3, "Fulfillment Staff"),
                ],
                default=2,
                verbose_name="Role",
            ),
        ),
        migrations.CreateModel(
            name="CombineLabelTask",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1000),
                        default=list,
                        size=None,
                    ),
                ),
                ("total_urls", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Đang chờ xử lý"),
                            ("PROCESSING", "Đang xử lý"),
                            ("COMPLETED", "Hoàn thành"),
                            ("FAILED", "Thất bại"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("successful_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                (
                    "successful_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1000),
                        default=list,
                        size=None,
                    ),
                ),
                ("failed_urls", models.JSONField(default=list)),
                (
                    "drive_link",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combine_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "combine_label_tasks",
                "ordering": ["-created_at"],
            },
        ),
    ]
